#!/bin/sh

#clean up existing
rm *.html *.png *.PNG *.jpg *.JPG *.gif *.GIF *.htm *.css

#get page, prereqs, etc and convert links
wget -p -k -nd -E -e "robots=off" http://jkealey.shade.ca:82/twiki/bin/view/ProjetSEG/HelpOnLine?skin=plain

#prepare temp file
mv ./Help*.html ./helponline_TMP.html

#remove <BASE> tags from file
grep -iv "<base" ./helponline_TMP.html > ./helponline.html

#cleanup
rm *_TMP*
