/* Generated By:JJTree&JavaCC: Do not edit this line. jUCMNavParserConstants.java */
package seg.jUCMNav.scenarios.parser;

public interface jUCMNavParserConstants {

    int EOF = 0;
    int AND = 19;
    int OR = 20;
    int XOR = 21;
    int EQUALS = 22;
    int DOUBLEEQUALS = 23;
    int NOTEQUALS = 24;
    int NOT = 25;
    int ASSIGNMENTOPERATOR = 26;
    int IF = 27;
    int ELSE = 28;
    int STATEMENTTERMINATOR = 29;
    int BOOLEAN = 30;
    int INTEGER = 31;
    int IDENTIFIER = 32;
    int LETTER = 33;
    int DIGIT = 34;

    int DEFAULT = 0;

    String[] tokenImage = { "<EOF>", //$NON-NLS-1$
            "\" \"", //$NON-NLS-1$
            "\"\\t\"", //$NON-NLS-1$
            "\"\\n\"", //$NON-NLS-1$
            "\"\\r\"", //$NON-NLS-1$
            "<token of kind 5>", //$NON-NLS-1$
            "<token of kind 6>", //$NON-NLS-1$
            "\"{\"", //$NON-NLS-1$
            "\"}\"", //$NON-NLS-1$
            "\"=>\"", //$NON-NLS-1$
            "\"(\"", //$NON-NLS-1$
            "\")\"", //$NON-NLS-1$
            "\">\"", //$NON-NLS-1$
            "\">=\"", //$NON-NLS-1$
            "\"<\"", //$NON-NLS-1$
            "\"<=\"", //$NON-NLS-1$
            "\"+\"", //$NON-NLS-1$
            "\"-\"", //$NON-NLS-1$
            "\"*\"", //$NON-NLS-1$
            "<AND>", //$NON-NLS-1$
            "<OR>", //$NON-NLS-1$
            "<XOR>", //$NON-NLS-1$
            "\"=\"", //$NON-NLS-1$
            "\"==\"", //$NON-NLS-1$
            "<NOTEQUALS>", //$NON-NLS-1$
            "<NOT>", //$NON-NLS-1$
            "\":=\"", //$NON-NLS-1$
            "\"if\"", //$NON-NLS-1$
            "\"else\"", //$NON-NLS-1$
            "\";\"", //$NON-NLS-1$
            "<BOOLEAN>", //$NON-NLS-1$
            "<INTEGER>", //$NON-NLS-1$
            "<IDENTIFIER>", //$NON-NLS-1$
            "<LETTER>", //$NON-NLS-1$
            "<DIGIT>", //$NON-NLS-1$
    };

}
