/* Generated By:JJTree&JavaCC: Do not edit this line. jUCMNavParserConstants.java */
package seg.jUCMNav.scenarios.parser;

public interface jUCMNavParserConstants {

  int EOF = 0;
  int AND = 19;
  int OR = 20;
  int XOR = 21;
  int EQUALS = 22;
  int DOUBLEEQUALS = 23;
  int NOTEQUALS = 24;
  int NOT = 25;
  int ASSIGNMENTOPERATOR = 26;
  int IF = 27;
  int ELSE = 28;
  int STATEMENTTERMINATOR = 29;
  int BOOLEAN = 30;
  int INTEGER = 31;
  int IDENTIFIER = 32;
  int LETTER = 33;
  int DIGIT = 34;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"{\"",
    "\"}\"",
    "\"=>\"",
    "\"(\"",
    "\")\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "<AND>",
    "<OR>",
    "<XOR>",
    "\"=\"",
    "\"==\"",
    "<NOTEQUALS>",
    "<NOT>",
    "\":=\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "<BOOLEAN>",
    "<INTEGER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
  };

}
