<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="grl"
    nsURI="http:///grl.ecore" nsPrefix="grl">
  <eClassifiers xsi:type="ecore:EClass" name="GRLspec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="urnspec" lowerBound="1"
        eType="ecore:EClass urn.ecore#//URNspec" transient="true" eOpposite="urn.ecore#//URNspec/grlspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intElements" upperBound="-1"
        eType="#//IntentionalElement" containment="true" eOpposite="#//IntentionalElement/grlspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1"
        eType="#//Actor" containment="true" eOpposite="#//Actor/grlspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//ElementLink" containment="true" eOpposite="#//ElementLink/grlspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluationGroups" upperBound="-1"
        eType="#//EvaluationGroup" containment="true" eOpposite="#//EvaluationGroup/grlspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//EvaluationScenario" containment="true" eOpposite="#//EvaluationScenario/grlspec"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Belief" eSuperTypes="#//GRLNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntentionalElement" eSuperTypes="urncore.ecore#//GRLmodelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//IntentionalElementType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="criticality" eType="#//Criticality"
        defaultValueLiteral="Medium"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="#//Priority"
        defaultValueLiteral="Medium"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decompositionType" eType="#//DecompositionType"
        defaultValueLiteral="And"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grlspec" lowerBound="1"
        eType="#//GRLspec" transient="true" eOpposite="#//GRLspec/intElements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" upperBound="-1" eType="#//IntentionalElementRef"
        eOpposite="#//IntentionalElementRef/def"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evals" upperBound="-1"
        eType="#//Evaluation" eOpposite="#//Evaluation/intElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksSrc" upperBound="-1"
        eType="#//ElementLink" eOpposite="#//ElementLink/src"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksDest" upperBound="-1"
        eType="#//ElementLink" eOpposite="#//ElementLink/dest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="urncore.ecore#//GRLmodelElement urncore.ecore#//IURNContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="grlspec" lowerBound="1"
        eType="#//GRLspec" transient="true" eOpposite="#//GRLspec/actors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Criticality">
    <eLiterals name="High"/>
    <eLiterals name="Medium" value="1"/>
    <eLiterals name="Low" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="IntentionalElementType">
    <eLiterals name="Softgoal"/>
    <eLiterals name="Goal" value="1"/>
    <eLiterals name="Task" value="2"/>
    <eLiterals name="Ressource" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="High"/>
    <eLiterals name="Medium" value="1"/>
    <eLiterals name="Low" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GRLGraph" eSuperTypes="urncore.ecore#//GRLmodelElement urncore.ecore#//IURNDiagram"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActorRef" eSuperTypes="urncore.ecore#//GRLmodelElement urncore.ecore#//IURNContainerRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntentionalElementRef" eSuperTypes="#//GRLNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="def" lowerBound="1" eType="#//IntentionalElement"
        eOpposite="#//IntentionalElement/refs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contribution" eSuperTypes="#//ElementLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contribution" eType="#//ContributionType"
        defaultValueLiteral="Unknown"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correlation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContributionType">
    <eLiterals name="Make"/>
    <eLiterals name="Help" value="1"/>
    <eLiterals name="SomePositive" value="2"/>
    <eLiterals name="Unknown" value="3"/>
    <eLiterals name="SomeNegative" value="4"/>
    <eLiterals name="Hurt" value="5"/>
    <eLiterals name="Break" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkRef" eSuperTypes="urncore.ecore#//IURNConnection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" lowerBound="1" eType="#//ElementLink"
        eOpposite="#//ElementLink/refs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendpoints" upperBound="-1"
        eType="#//LinkRefBendpoint" containment="true" eOpposite="#//LinkRefBendpoint/linkref"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementLink" eSuperTypes="urncore.ecore#//GRLmodelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refs" upperBound="-1" eType="#//LinkRef"
        eOpposite="#//LinkRef/link"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grlspec" lowerBound="1"
        eType="#//GRLspec" transient="true" eOpposite="#//GRLspec/links"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" lowerBound="1" eType="#//IntentionalElement"
        eOpposite="#//IntentionalElement/linksSrc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//IntentionalElement"
        eOpposite="#//IntentionalElement/linksDest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Decomposition" eSuperTypes="#//ElementLink"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency" eSuperTypes="#//ElementLink"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DecompositionType">
    <eLiterals name="And"/>
    <eLiterals name="Or" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evaluation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="evaluation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intElement" lowerBound="1"
        eType="#//IntentionalElement" eOpposite="#//IntentionalElement/evals"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenario" lowerBound="1"
        eType="#//EvaluationScenario" transient="true" eOpposite="#//EvaluationScenario/evaluations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationScenario" eSuperTypes="urncore.ecore#//GRLmodelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="evaluations" upperBound="-1"
        eType="#//Evaluation" containment="true" eOpposite="#//Evaluation/scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groups" lowerBound="1"
        upperBound="-1" eType="#//EvaluationGroup" eOpposite="#//EvaluationGroup/scenarios"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grlspec" lowerBound="1"
        eType="#//GRLspec" transient="true" eOpposite="#//GRLspec/scenarios"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GRLNode" eSuperTypes="urncore.ecore#//GRLmodelElement urncore.ecore#//IURNNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinkRefBendpoint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkref" lowerBound="1"
        eType="#//LinkRef" transient="true" eOpposite="#//LinkRef/bendpoints"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeliefLink" eSuperTypes="urncore.ecore#//IURNConnection"/>
  <eClassifiers xsi:type="ecore:EClass" name="EvaluationGroup" eSuperTypes="urncore.ecore#//GRLmodelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//EvaluationScenario" eOpposite="#//EvaluationScenario/groups"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="grlspec" lowerBound="1"
        eType="#//GRLspec" transient="true" eOpposite="#//GRLspec/evaluationGroups"/>
  </eClassifiers>
</ecore:EPackage>
