<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ucm"
    nsURI="http:///seg/jUCMNav/model/ucm.ecore" nsPrefix="seg.jUCMNav.model.ucm">
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" lowerBound="1" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/path"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inFork" lowerBound="1"
        eType="#//Fork" eOpposite="#//Fork/inPaths"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outFork" lowerBound="1"
        eType="#//Fork" eOpposite="#//Fork/outPath"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//UcmDiagram" eOpposite="#//UcmDiagram/paths"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endpoint" lowerBound="1"
        eType="#//EndPoint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startpoint" lowerBound="1"
        eType="#//StartPoint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//XYElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//UcmDiagram" eOpposite="#//UcmDiagram/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upLink" eType="#//Link"
        eOpposite="#//Link/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="downLink" eType="#//Link"
        eOpposite="#//Link/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="path" lowerBound="1" eType="#//Path"
        eOpposite="#//Path/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" lowerBound="1" eType="#//Node"
        eOpposite="#//Node/previous"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/next"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="XYElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="#//Component"
        eOpposite="#//Component/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//SizedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//XYElement" eOpposite="#//XYElement/component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//UcmDiagram" eOpposite="#//UcmDiagram/components"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SizedElement" eSuperTypes="#//XYElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UcmDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forks" upperBound="-1"
        eType="#//Fork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true" eOpposite="#//Component/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//Path" containment="true" eOpposite="#//Path/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPaths" lowerBound="1"
        upperBound="-1" eType="#//Path" eOpposite="#//Path/inFork"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outPath" upperBound="-1"
        eType="#//Path" eOpposite="#//Path/outFork"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/upLink"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Node" eOpposite="#//Node/downLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndPoint" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="StartPoint" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Responsibility" eSuperTypes="#//Node"/>
</ecore:EPackage>
