<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ucm"
    nsURI="http:///ucm.ecore" nsPrefix="ucm">
  <eClassifiers xsi:type="ecore:EClass" name="UCMspec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="urnspec" lowerBound="1"
        eType="ecore:EClass urn.ecore#//URNspec" transient="true" eOpposite="urn.ecore#//URNspec/ucmspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resptimereq" upperBound="-1"
        eType="#//performance/ResponseTimeReq" containment="true" eOpposite="#//performance/ResponseTimeReq/ucmspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perfMeasures" upperBound="-1"
        eType="#//performance/PerfMeasure" containment="true" eOpposite="#//performance/PerfMeasure/ucmspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//performance/GeneralResource" containment="true" eOpposite="#//performance/GeneralResource/ucmspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioGroups" upperBound="-1"
        eType="#//scenario/ScenarioGroup" containment="true" eOpposite="#//scenario/ScenarioGroup/ucmspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//scenario/Variable" containment="true" eOpposite="#//scenario/Variable/ucmspec"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationTypes" upperBound="-1"
        eType="#//scenario/EnumerationType" containment="true" eOpposite="#//scenario/EnumerationType/ucmspec"/>
  </eClassifiers>
  <eSubpackages name="performance" nsURI="http:///ucm/performance.ecore" nsPrefix="ucm.performance">
    <eClassifiers xsi:type="ecore:EClass" name="Timestamp" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
          eType="#//performance/ResponseTimeReq" eOpposite="#//performance/ResponseTimeReq/ts1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
          eType="#//performance/ResponseTimeReq" eOpposite="#//performance/ResponseTimeReq/ts2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResponseTimeReq" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ucmspec" lowerBound="1"
          eType="#//UCMspec" transient="true" eOpposite="#//UCMspec/resptimereq"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ts1" lowerBound="1" eType="#//performance/Timestamp"
          eOpposite="#//performance/Timestamp/targets"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ts2" lowerBound="1" eType="#//performance/Timestamp"
          eOpposite="#//performance/Timestamp/sources"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DeviceKind">
      <eLiterals name="Processor"/>
      <eLiterals name="Disk" value="1"/>
      <eLiterals name="DSP" value="2"/>
      <eLiterals name="Other" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PerfValueKind">
      <eLiterals name="Mean"/>
      <eLiterals name="Variance" value="1"/>
      <eLiterals name="Percentile" value="2"/>
      <eLiterals name="Moment" value="3"/>
      <eLiterals name="Min" value="4"/>
      <eLiterals name="Max" value="5"/>
      <eLiterals name="Distribution" value="6"/>
      <eLiterals name="Unknown" value="7"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PerfValueSource">
      <eLiterals name="Required"/>
      <eLiterals name="Assumed" value="1"/>
      <eLiterals name="Predicted" value="2"/>
      <eLiterals name="Measured" value="3"/>
      <eLiterals name="Unknown" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArrivalProcess">
      <eLiterals name="PoissonPDF"/>
      <eLiterals name="Periodic" value="1"/>
      <eLiterals name="Uniform" value="2"/>
      <eLiterals name="PhaseType" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PerfAttribute">
      <eLiterals name="Delay"/>
      <eLiterals name="Throughput" value="1"/>
      <eLiterals name="Utilization" value="2"/>
      <eLiterals name="Interval" value="3"/>
      <eLiterals name="Wait" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Workload" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="closed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalPattern" eType="#//performance/ArrivalProcess"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalParam1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalParam2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="coeffVarSeq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="population" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startPoint" lowerBound="1"
          eType="#//map/StartPoint" transient="true" eOpposite="#//map/StartPoint/workload"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="respTime" upperBound="-1"
          eType="#//performance/PerfMeasure" eOpposite="#//performance/PerfMeasure/duration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GeneralResource" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ucmspec" lowerBound="1"
          eType="#//UCMspec" transient="true" eOpposite="#//UCMspec/resources"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="demands" upperBound="-1"
          eType="#//performance/Demand" eOpposite="#//performance/Demand/resource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PerfMeasure" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="measure" eType="#//performance/PerfAttribute"
          defaultValueLiteral="Delay"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ucmspec" lowerBound="1"
          eType="#//UCMspec" transient="true" eOpposite="#//UCMspec/perfMeasures"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="perfValues" upperBound="-1"
          eType="#//performance/PerfValue" containment="true" eOpposite="#//performance/PerfValue/perfMeasure"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="duration" eType="#//performance/Workload"
          eOpposite="#//performance/Workload/respTime"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PerfValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//performance/PerfValueKind"
          defaultValueLiteral="Unknown"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="#//performance/PerfValueSource"
          defaultValueLiteral="Unknown"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kthMoment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="perfMeasure" lowerBound="1"
          eType="#//performance/PerfMeasure" transient="true" eOpposite="#//performance/PerfMeasure/perfValues"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActiveResource" eSuperTypes="#//performance/GeneralResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="0.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PassiveResource" eSuperTypes="#//performance/GeneralResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="ecore:EClass urncore.ecore#//ComponentElement"
          eOpposite="urncore.ecore#//ComponentElement/resource"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalOperation" eSuperTypes="#//performance/ActiveResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProcessingResource" eSuperTypes="#//performance/ActiveResource">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//performance/DeviceKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
          eType="ecore:EClass urncore.ecore#//ComponentRegular" eOpposite="urncore.ecore#//ComponentRegular/host"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Demand">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="responsibility" lowerBound="1"
          eType="ecore:EClass urncore.ecore#//Responsibility" transient="true" eOpposite="urncore.ecore#//Responsibility/demands"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          eType="#//performance/GeneralResource" eOpposite="#//performance/GeneralResource/demands"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="map" nsURI="http:///ucm/map.ecore" nsPrefix="ucm.map">
    <eClassifiers xsi:type="ecore:EClass" name="AndJoin" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OutBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
          eType="#//map/PluginBinding" transient="true" eOpposite="#//map/PluginBinding/out"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endPoint" lowerBound="1"
          eType="#//map/EndPoint" eOpposite="#//map/EndPoint/outBindings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stubExit" lowerBound="1"
          eType="#//map/NodeConnection" eOpposite="#//map/NodeConnection/outBindings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
          eType="#//map/PluginBinding" transient="true" eOpposite="#//map/PluginBinding/in"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startPoint" lowerBound="1"
          eType="#//map/StartPoint" eOpposite="#//map/StartPoint/inBindings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stubEntry" lowerBound="1"
          eType="#//map/NodeConnection" eOpposite="#//map/NodeConnection/inBindings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RespRef" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitionCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="respDef" lowerBound="1"
          eType="ecore:EClass urncore.ecore#//Responsibility" eOpposite="urncore.ecore#//Responsibility/respRefs"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrJoin" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrFork" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Connect" eSuperTypes="#//map/PathNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="NodeConnection" eSuperTypes="urncore.ecore#//IURNConnection">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="1.0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inBindings" upperBound="-1"
          eType="#//map/InBinding" eOpposite="#//map/InBinding/stubEntry"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outBindings" upperBound="-1"
          eType="#//map/OutBinding" eOpposite="#//map/OutBinding/stubExit"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass urncore.ecore#//Condition"
          containment="true" eOpposite="urncore.ecore#//Condition/nodeConnection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WaitingPlace" eSuperTypes="#//map/PathNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" A waiting place has one source hyperedge and one target  hyperedge, or two target hyperedges when there is a timeout  path. This is not a strict constraint as other hyperedges (e.g.,  connect) might be linked to it. The triggering-event-list gives  the set of events that restart the sequence of actions in a  path. The precondition-list must be satisfied in order for the  sequence to restart.ATTRIBUTE wait-type: user given typeATTRIBUTE logical-condition: expression which is evaluated at run timeATTRIBUTE timeout-variable: reference to a timer's timeout variable"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="waitType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Stub" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynamic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shared" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//map/PluginBinding" containment="true" eOpposite="#//map/PluginBinding/stub"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PathNode" abstract="true" eSuperTypes="urncore.ecore#//UCMmodelElement urncore.ecore#//IURNNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="EndPoint" eSuperTypes="#//map/PathNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An end-point (or end bar, or result) has usually one  source hyperedge (and possibly a target hyperedge to a connect  for linking to starts or waiting places). The  resulting-event-list gives the set of events that occur once the  sequence of actions in a path are completed. The  postcondition-list must be satisfied once the sequence is  completed. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outBindings" upperBound="-1"
          eType="#//map/OutBinding" eOpposite="#//map/OutBinding/endPoint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postcondition" eType="ecore:EClass urncore.ecore#//Condition"
          containment="true" eOpposite="urncore.ecore#//Condition/endPoint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioEndPoints" upperBound="-1"
          eType="#//scenario/ScenarioEndPoint" eOpposite="#//scenario/ScenarioEndPoint/endPoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StartPoint" eSuperTypes="#//map/PathNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A start of path should have only one target hyperedge.  It may have a source when linked to a result by a 'connect'. The  triggering-event-list gives the set of events that initiate the  sequence of actions in a path. The precondition-list must be  satisfied in order for the scenario to start&#xD;&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="workload" eType="#//performance/Workload"
          containment="true" eOpposite="#//performance/Workload/startPoint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inBindings" upperBound="-1"
          eType="#//map/InBinding" eOpposite="#//map/InBinding/startPoint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="ecore:EClass urncore.ecore#//Condition"
          containment="true" eOpposite="urncore.ecore#//Condition/startPoint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioStartPoints"
          upperBound="-1" eType="#//scenario/ScenarioStartPoint" eOpposite="#//scenario/ScenarioStartPoint/startPoint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UCMmap" eSuperTypes="urncore.ecore#//UCMmodelElement urncore.ecore#//IURNDiagram">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentStub" upperBound="-1"
          eType="#//map/PluginBinding" eOpposite="#//map/PluginBinding/plugin"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Abort" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Condition" upperBound="-1"
          eType="ecore:EClass urncore.ecore#//Condition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PluginBinding">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A plugin refers to a Map that can be substituted  to the parent stub. The binding between the plugin and its  parent stub is defined by the in-connections, the  out-connections, and the instance-values. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitionCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
          defaultValueLiteral="1.0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" upperBound="-1"
          eType="#//map/InBinding" containment="true" eOpposite="#//map/InBinding/binding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="out" lowerBound="1" upperBound="-1"
          eType="#//map/OutBinding" containment="true" eOpposite="#//map/OutBinding/binding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stub" eType="#//map/Stub"
          transient="true" eOpposite="#//map/Stub/bindings"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="plugin" lowerBound="1"
          eType="#//map/UCMmap" eOpposite="#//map/UCMmap/parentStub"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="ecore:EClass urncore.ecore#//Condition"
          containment="true" eOpposite="urncore.ecore#//Condition/pluginBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentRef" eSuperTypes="urncore.ecore#//UCMmodelElement urncore.ecore#//IURNContainerRef">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A reference to a component or pool in a particular map."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="replicationFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="anchored" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Timer" eSuperTypes="#//map/WaitingPlace">
      <eStructuralFeatures xsi:type="ecore:EReference" name="timeoutPath" eType="#//map/NodeConnection"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AndFork" eSuperTypes="#//map/PathNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EmptyPoint" eSuperTypes="#//map/PathNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="FailurePoint" eSuperTypes="#//map/PathNode"/>
    <eClassifiers xsi:type="ecore:EClass" name="DirectionArrow" eSuperTypes="#//map/PathNode"/>
  </eSubpackages>
  <eSubpackages name="scenario" nsURI="http:///ucm/scenario.ecore" nsPrefix="ucm.scenario">
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Variable definition"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="boolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ucmspec" lowerBound="1"
          eType="#//UCMspec" transient="true" eOpposite="#//UCMspec/variables"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumerationType" eType="#//scenario/EnumerationType"
          eOpposite="#//scenario/EnumerationType/instances"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScenarioDef" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines initial values for the variables, the expected postconditions, the end points, and the start points.&#xD;&#xA;"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="group" lowerBound="1"
          eType="#//scenario/ScenarioGroup" transient="true" eOpposite="#//scenario/ScenarioGroup/scenarios"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentScenarios" upperBound="-1"
          eType="#//scenario/ScenarioDef" eOpposite="#//scenario/ScenarioDef/includedScenarios"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includedScenarios" upperBound="-1"
          eType="#//scenario/ScenarioDef" eOpposite="#//scenario/ScenarioDef/parentScenarios"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="preconditions" upperBound="-1"
          eType="ecore:EClass urncore.ecore#//Condition" containment="true" eOpposite="urncore.ecore#//Condition/scenarioDefPre"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="postconditions" upperBound="-1"
          eType="ecore:EClass urncore.ecore#//Condition" containment="true" eOpposite="urncore.ecore#//Condition/scenarioDefPost"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="initializations" upperBound="-1"
          eType="#//scenario/Initialization" containment="true" eOpposite="#//scenario/Initialization/scenarioDef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startPoints" upperBound="-1"
          eType="#//scenario/ScenarioStartPoint" containment="true" eOpposite="#//scenario/ScenarioStartPoint/scenarioDef"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endPoints" upperBound="-1"
          eType="#//scenario/ScenarioEndPoint" containment="true" eOpposite="#//scenario/ScenarioEndPoint/scenarioDef"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScenarioGroup" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Group of related scenario definitions."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ucmspec" lowerBound="1"
          eType="#//UCMspec" transient="true" eOpposite="#//UCMspec/scenarioGroups"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
          eType="#//scenario/ScenarioDef" containment="true" eOpposite="#//scenario/ScenarioDef/group"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationType" eSuperTypes="urncore.ecore#//UCMmodelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ucmspec" lowerBound="1"
          eType="#//UCMspec" transient="true" eOpposite="#//UCMspec/enumerationTypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
          eType="#//scenario/Variable" eOpposite="#//scenario/Variable/enumerationType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Initialization">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioDef" lowerBound="1"
          eType="#//scenario/ScenarioDef" transient="true" eOpposite="#//scenario/ScenarioDef/initializations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//scenario/Variable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScenarioStartPoint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioDef" lowerBound="1"
          eType="#//scenario/ScenarioDef" transient="true" eOpposite="#//scenario/ScenarioDef/startPoints"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="startPoint" lowerBound="1"
          eType="#//map/StartPoint" eOpposite="#//map/StartPoint/scenarioStartPoints"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ScenarioEndPoint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="mandatory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioDef" lowerBound="1"
          eType="#//scenario/ScenarioDef" transient="true" eOpposite="#//scenario/ScenarioDef/endPoints"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="endPoint" lowerBound="1"
          eType="#//map/EndPoint" eOpposite="#//map/EndPoint/scenarioEndPoints"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
