<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="urncore"
    nsURI="http:///urncore.ecore" nsPrefix="urncore">
  <eClassifiers xsi:type="ecore:EClass" name="URNdefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="urnspec" lowerBound="1"
        eType="ecore:EClass urn.ecore#//URNspec" transient="true" eOpposite="urn.ecore#//URNspec/urndef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibilities" upperBound="-1"
        eType="#//Responsibility" containment="true" eOpposite="#//Responsibility/urndefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//ComponentElement" containment="true" eOpposite="#//ComponentElement/urndefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specDiagrams" upperBound="-1"
        eType="#//IURNDiagram" containment="true" eOpposite="#//IURNDiagram/urndefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concerns" upperBound="-1"
        eType="#//Concern" containment="true" eOpposite="#//Concern/urndefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Responsibility" eSuperTypes="#//UCMmodelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="empty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="urndefinition" lowerBound="1"
        eType="#//URNdefinition" transient="true" eOpposite="#//URNdefinition/responsibilities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="demands" upperBound="-1"
        eType="ecore:EClass ucm.ecore#//performance/Demand" containment="true" eOpposite="ucm.ecore#//performance/Demand/responsibility"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="respRefs" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ucm.ecore#//map/RespRef" eOpposite="ucm.ecore#//map/RespRef/respDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentRegular" abstract="true" eSuperTypes="#//ComponentElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="ComponentRegular can be protected (e.g., by a semaphone) or not. Dynamic components have the slot attribute set to true. ComponentRegular can include sub-components."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ComponentKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="protected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="slot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedComponent" upperBound="-1"
        eType="#//ComponentElement" eOpposite="#//ComponentElement/includingComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" eType="ecore:EClass ucm.ecore#//performance/ProcessingResource"
        eOpposite="ucm.ecore#//performance/ProcessingResource/components"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentKind">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Correspond to the component types defined originally for Use Case Maps by Buhr et al."/>
    </eAnnotations>
    <eLiterals name="Team"/>
    <eLiterals name="Object" value="1"/>
    <eLiterals name="Process" value="2"/>
    <eLiterals name="Agent" value="3"/>
    <eLiterals name="Actor" value="4"/>
    <eLiterals name="Other" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentElement" abstract="true" eSuperTypes="#//UCMmodelElement #//IURNContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract class for ComponentType, Component (instances), and Pools."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="urndefinition" lowerBound="1"
        eType="#//URNdefinition" transient="true" eOpposite="#//URNdefinition/components"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includingComponent" eType="#//ComponentRegular"
        eOpposite="#//ComponentRegular/includedComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" eType="ecore:EClass ucm.ecore#//performance/PassiveResource"
        eOpposite="ucm.ecore#//performance/PassiveResource/component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pool" eSuperTypes="#//ComponentElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Pools are containers for data or dynamic components. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ofComponents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentType" eType="#//ComponentType"
        eOpposite="#//ComponentType/pools"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dynResponsibilities" upperBound="-1"
        eType="#//DynamicResponsibility" eOpposite="#//DynamicResponsibility/pool"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="#//ComponentRegular">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Component instance, which can be of a specific ComponentType."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ComponentType"
        eOpposite="#//ComponentType/instances"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentType" eSuperTypes="#//ComponentRegular">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="User-defined component type. Type hiearchies (trees) can also be created."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subType" upperBound="-1"
        eType="#//ComponentType" eOpposite="#//ComponentType/superType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//ComponentType"
        eOpposite="#//ComponentType/subType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Component" eOpposite="#//Component/type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pools" upperBound="-1"
        eType="#//Pool" eOpposite="#//Pool/componentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicResponsibility" eSuperTypes="#//Responsibility">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="TBD."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//DynamicRespKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrowLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pool" eType="#//Pool" eOpposite="#//Pool/dynResponsibilities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UCMmodelElement" abstract="true" eSuperTypes="#//URNmodelElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DynamicRespKind">
    <eLiterals name="Move"/>
    <eLiterals name="MoveStay" value="1"/>
    <eLiterals name="Create" value="2"/>
    <eLiterals name="Copy" value="3"/>
    <eLiterals name="Destroy" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GRLmodelElement" abstract="true" eSuperTypes="#//URNmodelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeLabel" eSuperTypes="#//Label">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//IURNNode"
        transient="true" eOpposite="#//IURNNode/label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deltaX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deltaY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentLabel" eSuperTypes="#//Label">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contRef" eType="#//IURNContainerRef"
        transient="true" eOpposite="#//IURNContainerRef/label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPoint" eType="ecore:EClass ucm.ecore#//map/StartPoint"
        transient="true" eOpposite="ucm.ecore#//map/StartPoint/precondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endPoint" eType="ecore:EClass ucm.ecore#//map/EndPoint"
        transient="true" eOpposite="ucm.ecore#//map/EndPoint/postcondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pluginBinding" eType="ecore:EClass ucm.ecore#//map/PluginBinding"
        transient="true" eOpposite="ucm.ecore#//map/PluginBinding/precondition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeConnection" eType="ecore:EClass ucm.ecore#//map/NodeConnection"
        transient="true" eOpposite="ucm.ecore#//map/NodeConnection/condition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioDefPre" eType="ecore:EClass ucm.ecore#//scenario/ScenarioDef"
        transient="true" eOpposite="ucm.ecore#//scenario/ScenarioDef/preconditions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarioDefPost" eType="ecore:EClass ucm.ecore#//scenario/ScenarioDef"
        transient="true" eOpposite="ucm.ecore#//scenario/ScenarioDef/postconditions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IURNDiagram" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="urndefinition" lowerBound="1"
        eType="#//URNdefinition" transient="true" eOpposite="#//URNdefinition/specDiagrams"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//IURNNode" containment="true" eOpposite="#//IURNNode/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contRefs" upperBound="-1"
        eType="#//IURNContainerRef" containment="true" eOpposite="#//IURNContainerRef/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//IURNConnection" containment="true" eOpposite="#//IURNConnection/diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concern" eType="#//Concern"
        eOpposite="#//Concern/specDiagrams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="URNmodelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromLinks" upperBound="-1"
        eType="ecore:EClass urn.ecore#//URNlink" eOpposite="urn.ecore#//URNlink/fromElem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLinks" upperBound="-1"
        eType="ecore:EClass urn.ecore#//URNlink" eOpposite="urn.ecore#//URNlink/toElem"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" upperBound="-1"
        eType="#//Metadata" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IURNNode" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//IURNDiagram" transient="true" eOpposite="#//IURNDiagram/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contRef" eType="#//IURNContainerRef"
        eOpposite="#//IURNContainerRef/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="succ" upperBound="-1" eType="#//IURNConnection"
        eOpposite="#//IURNConnection/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pred" upperBound="-1" eType="#//IURNConnection"
        eOpposite="#//IURNConnection/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" eType="#//NodeLabel"
        containment="true" eOpposite="#//NodeLabel/node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IURNContainerRef" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//IURNDiagram" transient="true" eOpposite="#//IURNDiagram/contRefs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contDef" lowerBound="1"
        eType="#//IURNContainer" eOpposite="#//IURNContainer/contRefs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//IURNNode" eOpposite="#//IURNNode/contRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="#//ComponentLabel"
        containment="true" eOpposite="#//ComponentLabel/contRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//IURNContainerRef"
        eOpposite="#//IURNContainerRef/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//IURNContainerRef" eOpposite="#//IURNContainerRef/parent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IURNContainer" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fillColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contRefs" upperBound="-1"
        eType="#//IURNContainerRef" eOpposite="#//IURNContainerRef/contDef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IURNConnection" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//IURNNode" eOpposite="#//IURNNode/succ"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//IURNNode" eOpposite="#//IURNNode/pred"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagram" lowerBound="1"
        eType="#//IURNDiagram" transient="true" eOpposite="#//IURNDiagram/connections"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metadata">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concern" eSuperTypes="#//URNmodelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="urndefinition" lowerBound="1"
        eType="#//URNdefinition" transient="true" eOpposite="#//URNdefinition/concerns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specDiagrams" upperBound="-1"
        eType="#//IURNDiagram" eOpposite="#//IURNDiagram/concern"/>
  </eClassifiers>
</ecore:EPackage>
